version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: bencollinsuk/world-bike-map-tile-server-db
    environment:
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGDATA=/var/lib/postgresql/data
      - PGPASSWORD=renderer
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=renderer
      - POSTGRES_USER=renderer
      - THREADS=4
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 2G
    ports:
      - "5432:5432"
  import:
    build:
      context: .
      dockerfile: Dockerfile.import
    image: world-bike-map-tile-server-import:latest
    depends_on:
      - db
    volumes:
      - /home/shared/united-kingdom-latest.osm.pbf:/data.osm.pbf
    environment:
      - PGUSER=renderer
      - PGPASSWORD=renderer
      - PGHOST=db
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf
      - WGET_ARGS=--quiet
      - DOWNLOAD_POLY=
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 2G
    command: "import"
  map:
    build:
      context: .
      dockerfile: Dockerfile.map
    image: world-bike-map-tile-server-map:latest
    depends_on:
      - db
    volumes:
      - osm-tiles:/var/cache/renderd/tiles
    environment:
      - ALLOW_CORS=1
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGHOST=db
      - PGPASSWORD=renderer
      - PGUSER=renderer
      - THREADS=2
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2G
    ports:
      - "8080:80"
    command: "run"
  render:
    build:
      context: .
      dockerfile: Dockerfile.render
    image: world-bike-map-tile-server-render:latest
    depends_on:
      - db
    volumes:
      - osm-tiles:/var/cache/renderd/tiles
    environment:
      - THREADS=12
    deploy:
      resources:
        reservations:
          cpus: '12'
          memory: 8G
    command: "render"

volumes:
  osm-tiles:
    external: true
  osm-data:
    external: true
