version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: bencollinsuk/world-bike-map-tile-server-db
    volumes:
      - ./scripts/db.sh:/db.sh
      - osm-data:/var/lib/postgresql/12/main
    environment:
      - THREADS=4
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGPASSWORD=renderer
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 2G
    ports:
      - "5432:5432"
    command: "db"
  import:
    build:
      context: .
      dockerfile: Dockerfile.map
    image: bencollinsuk/world-bike-map-tile-server-map
    depends_on:
      - db
    volumes:
      - ./scripts/map.sh:/map.sh
      - /home/shared/luxembourg-latest.osm.pbf:/data.osm.pbf
    environment:
      - PGUSER=renderer
      - PGPASSWORD=renderer
      - PGHOST=db
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 2G
    command: "import"
  map:
    build:
      context: .
      dockerfile: Dockerfile-map
    image: bencollinsuk/world-bike-map-tile-server-map
    depends_on:
      - db
    volumes:
      - ./scripts/map.sh:/map.sh
      - osm-tiles:/var/cache/renderd/tiles
    environment:
      - THREADS=2
      - ALLOW_CORS=1
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=renderer
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2G
    ports:
      - "8080:80"
    command: "run"
  render:
    build:
      context: .
      dockerfile: Dockerfile-map
    image: bencollinsuk/world-bike-map-tile-server-map
    depends_on:
      - db
    volumes:
      - ./scripts/map.sh:/map.sh
      - osm-tiles:/var/cache/renderd/tiles
    environment:
      - THREADS=12
    deploy:
      resources:
        reservations:
          cpus: '12'
          memory: 8G
    command: "render"

volumes:
  osm-tiles:
    external: true
  osm-data:
    external: true
