version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: world-bike-map-tile-server-db
    environment:
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGDATA=/var/lib/postgresql/data
      - PGPASSWORD=renderer
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=renderer
      - POSTGRES_USER=renderer
      - THREADS=4
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 2G
    ports:
      - "5432:5432"

  import:
    command: ["import"]
    build:
      context: .
      dockerfile: Dockerfile
    image: world-bike-map-tile-server
    depends_on:
      - db
    volumes:
      - osm-data:/osm-data
      - osm-tiles:/var/lib/mod_tile
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf
      - WGET_ARGS=--quiet
      - DOWNLOAD_POLY=
      - MAX_ZOOM=15
      - ALLOW_CORS=1
    deploy:
      resources:
        reservations:
          cpus: '12'
          memory: 2G
  server:
    command: ["server"]
    build:
      context: .
      dockerfile: Dockerfile
    image: world-bike-map-tile-server
    depends_on:
      - db
    volumes:
      - osm-data:/osm-data
      - osm-tiles:/var/lib/mod_tile
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf
      - WGET_ARGS=--quiet
      - DOWNLOAD_POLY=
      - MAX_ZOOM=15
      - ALLOW_CORS=1
    deploy:
      resources:
        reservations:
          cpus: '12'
          memory: 2G
    ports:
      - "8080:80"

volumes:
  osm-tiles:
  osm-data:
