name: Docker

on:
  create:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: bencollinsuk/world-bike-map-tile-server-cyclosm
        tag_with_ref: true
        tags: latest
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
